/* ============================================================
   Tout le contenu des jeux. Pour ajouter une question, il suffit
   d'ajouter une ligne dans la bonne liste (entre guillemets simples,
   avec une virgule à la fin). L'apostrophe ’ est la typographique :
   elle ne casse rien, contrairement à l'apostrophe droite.
   ============================================================ */
globalThis.CONTENU = {

  /* ---------- Tu préfères… (deux choix) ---------- */
  preferes: [
    ['Un câlin de 10 minutes', 'Dix bisous express'],
    ['Un petit-déjeuner au lit', 'Un dîner aux chandelles'],
    ['Recevoir une lettre d’amour', 'Recevoir un message vocal d’amour'],
    ['Une soirée plaid et film', 'Une soirée à danser'],
    ['Un surnom tout mignon', 'Un surnom ridicule mais rien qu’à nous'],
    ['Se tenir la main partout', 'Des câlins surprises à tout moment'],
    ['Un rendez-vous au coucher du soleil', 'Un rendez-vous sous les étoiles'],
    ['Cuisiner ensemble', 'Commander et manger devant une série'],
    ['Un pique-nique au parc', 'Un pique-nique sur la plage'],
    ['Une photo souvenir chaque jour', 'Une vidéo souvenir chaque mois'],
    ['Recevoir des fleurs', 'Recevoir des bonbons'],
    ['Une surprise préparée pendant des semaines', 'Une surprise improvisée le jour même'],
    ['S’endormir en cuillère', 'S’endormir main dans la main'],
    ['Un week-end à la montagne', 'Un week-end à la mer'],
    ['Une chanson écrite pour toi', 'Un dessin fait pour toi'],
    ['Un film d’horreur blottis sous le plaid', 'Un dessin animé Disney'],
    ['Un bisou sur le front', 'Un bisou sur le nez'],
    ['Être réveillé(e) par des bisous', 'Être réveillé(e) par l’odeur des crêpes'],
    ['Un rendez-vous au cinéma', 'Un rendez-vous au bowling'],
    ['Une journée à Disneyland', 'Une journée au spa'],
    ['Écrire notre histoire dans un carnet', 'La raconter en photos'],
    ['Des chaussettes assorties', 'Des sweats assortis'],
    ['Un bracelet assorti', 'Un porte-clés assorti'],
    ['Un karaoké en duo', 'Une chorégraphie en duo'],
    ['Un road trip sans plan', 'Un voyage tout organisé'],
    ['Une journée entière sous la couette', 'Une journée entière dehors'],
    ['Pizza', 'Burger'],
    ['Sucré', 'Salé'],
    ['Crêpes', 'Gaufres'],
    ['Glace à la vanille', 'Glace au chocolat'],
    ['Sushis', 'Tacos'],
    ['Que des pâtes toute ta vie', 'Que du riz toute ta vie'],
    ['Chocolat noir', 'Chocolat au lait'],
    ['Petit-déjeuner sucré', 'Petit-déjeuner salé'],
    ['Pop-corn sucré', 'Pop-corn salé'],
    ['De l’ananas sur la pizza (Stitch approuve)', 'Jamais d’ananas sur la pizza'],
    ['Raclette', 'Fondue'],
    ['Un gâteau raté fait ensemble', 'Un gâteau parfait acheté en boutique'],
    ['Un fast-food à minuit', 'Un resto chic à midi'],
    ['Des bonbons qui piquent', 'Des guimauves toutes douces'],
    ['Pâte à tartiner', 'Confiture'],
    ['Des chips devant un film', 'Du chocolat devant un film'],
    ['Chocolat chaud', 'Thé glacé'],
    ['Des fraises', 'Des cerises'],
    ['Manger très épicé', 'Manger tout doux'],
    ['Pouvoir voler', 'Pouvoir te téléporter'],
    ['Lire dans les pensées', 'Devenir invisible'],
    ['Parler aux animaux', 'Parler toutes les langues du monde'],
    ['Avoir Stitch comme animal de compagnie', 'Avoir un petit dragon comme animal de compagnie'],
    ['Vivre dans un château', 'Vivre dans une cabane dans les arbres'],
    ['Voyager dans le passé', 'Voyager dans le futur'],
    ['Pouvoir arrêter le temps', 'Pouvoir revenir 10 secondes en arrière quand tu veux'],
    ['Ne plus jamais avoir froid', 'Ne plus jamais avoir chaud'],
    ['Une maison sur la plage', 'Une maison au milieu de la forêt'],
    ['Être un personnage Disney', 'Être un personnage de jeu vidéo'],
    ['Rétrécir à la taille d’une fourmi', 'Grandir jusqu’à 3 mètres (pendant une journée)'],
    ['Avoir les grandes oreilles de Stitch', 'Avoir une queue de sirène'],
    ['Pouvoir respirer sous l’eau', 'Pouvoir voir dans le noir'],
    ['Vivre à deux sur une île déserte', 'Vivre à deux dans une grande ville'],
    ['Savoir jouer de tous les instruments', 'Savoir danser toutes les danses'],
    ['Un million d’euros', 'Des câlins illimités pour toujours'],
    ['Changer de coiffure d’un claquement de doigts', 'Changer de tenue d’un claquement de doigts'],
    ['Un bouton pause pour la vie', 'Un bouton retour en arrière'],
    ['Des spaghettis à la place des cheveux', 'Des bras en guimauve'],
    ['Éternuer des paillettes', 'Faire des bulles de savon en riant'],
    ['Parler en chantant toute une journée', 'Parler en rimes toute une journée'],
    ['Avoir le hoquet pendant une journée', 'Avoir des fous rires incontrôlables pendant une journée'],
    ['Marcher comme un pingouin pendant une semaine', 'Parler comme un robot pendant une semaine'],
    ['Porter un déguisement de Stitch toute une journée', 'Chanter une chanson dans la rue'],
    ['Que tes pensées s’affichent au-dessus de ta tête', 'Que tes rêves passent à la télé'],
    ['Dormir dans un hamac pour toujours', 'Dormir sur un matelas à eau pour toujours'],
    ['Avoir une voix de canard pendant un jour', 'Avoir une voix de souris pendant un jour'],
    ['Être chatouilleux(se) de la tête aux pieds', 'Ne plus jamais pouvoir être chatouillé(e)'],
    ['Vivre sans musique', 'Vivre sans films'],
    ['Un mois sans téléphone', 'Un an sans chocolat'],
    ['Faire la vaisselle toute ta vie', 'Passer l’aspirateur toute ta vie'],
    ['Toujours 10 minutes en retard', 'Toujours 20 minutes en avance'],
    ['Plus jamais de grasse matinée', 'Plus jamais de sieste'],
    ['Du sable dans les chaussures pour toujours', 'Les cheveux mouillés pour toujours'],
    ['Un Stitch qui fait des bêtises chez toi', 'Un Pikly qui fait le ménage chez toi'],
    ['Danser le hula devant tout le monde', 'Chanter du Elvis devant tout le monde'],
    ['Hawaï', 'Le Japon'],
    ['Un voyage en avion', 'Un voyage en train de nuit'],
    ['Camper sous une tente', 'Un hôtel cinq étoiles'],
    ['Visiter un aquarium', 'Visiter un zoo'],
    ['Nager avec des tortues', 'Nager avec des dauphins'],
    ['Voir une aurore boréale', 'Voir une pluie d’étoiles filantes'],
    ['Paris', 'New York'],
    ['Faire du surf', 'Faire du paddle'],
    ['Une fête foraine', 'Un escape game'],
    ['Un concert', 'Un spectacle de magie'],
    ['Des vacances au soleil', 'Des vacances à la neige'],
    ['Un marché de Noël', 'Une fête de l’été'],
    ['Visiter un château', 'Explorer une grotte'],
    ['Une balade à cheval', 'Une balade en vélo tandem'],
    ['S’envoyer des messages toute la journée', 'Tout garder pour se le raconter le soir'],
    ['Fêter chaque mois ensemble', 'Fêter seulement les grandes dates'],
    ['Un cadeau cher', 'Un cadeau fait main'],
    ['Une dispute qui finit en fou rire', 'Jamais de dispute, mais jamais de fou rire non plus'],
    ['Choisir le film à chaque fois', 'Choisir le resto à chaque fois'],
    ['Que je te chante une chanson', 'Que je te fasse un massage'],
    ['Connaître la destination du prochain voyage', 'Garder la surprise jusqu’au bout'],
    ['Des vacances à deux', 'Des vacances avec des amis'],
    ['Un appel vidéo d’une heure', 'Un très long message'],
    ['Se voir une heure tous les jours', 'Une journée entière une fois par semaine'],
    ['Un plat cuisiné par moi (même raté)', 'Un plat de grand chef'],
    ['Un compliment sur ton style', 'Un compliment sur ton sourire'],
    ['Une soirée jeux de société', 'Une soirée karaoké'],
    ['Adopter un jour un chat', 'Adopter un jour un chien'],
    ['Un sapin de Noël énorme', 'Des guirlandes lumineuses partout'],
    ['Une bataille d’oreillers', 'Une bataille de chatouilles'],
    ['Un selfie parfait', 'Un selfie grimace'],
    ['Une chanson qui nous représente', 'Un film qui nous représente'],
    ['Se déguiser en Stitch et Angel', 'Se déguiser en Lilo et Stitch'],
    ['Un matin tout doux', 'Une grande soirée'],
    ['Faire les magasins ensemble', 'Faire du sport ensemble'],
    ['S’offrir des peluches', 'S’offrir des livres'],
    ['Se faire plein de surprises', 'Tout se dire à l’avance'],
    ['Une journée sans téléphone à deux', 'Une journée jeux vidéo à deux'],
    ['Dormir côté fenêtre', 'Dormir côté porte'],
    ['Être adopté(e) par Lilo', 'Être créé(e) par Jumba'],
    ['Avoir la force de Stitch', 'Avoir l’intelligence de Jumba'],
    ['Vivre dans la maison de Lilo à Hawaï', 'Vivre dans le vaisseau de Jumba'],
    ['Surfer avec Stitch', 'Danser le hula avec Lilo'],
    ['Avoir Souillon comme doudou', 'Avoir Pudge le poisson comme ami'],
    ['Le Lilo & Stitch dessin animé', 'Le Lilo & Stitch avec de vrais acteurs'],
    ['Un Stitch en peluche géant', 'Cent petits Stitch en peluche'],
    ['Être le/la meilleur(e) ami(e) de Stitch', 'Être le/la meilleur(e) ami(e) d’Angel'],
    ['Avoir les antennes d’Angel', 'Avoir les quatre bras de Stitch'],
    ['Vivre à Kauai', 'Vivre dans l’espace'],
    ['Un Noël version Disney', 'Un Halloween version Disney'],
    ['Se lever tôt pour voir le lever du soleil', 'Veiller tard pour voir les étoiles'],
    ['L’été', 'L’hiver'],
    ['La pluie contre la fenêtre', 'Le soleil sur la peau'],
    ['Une douche brûlante', 'Un bain moussant'],
    ['Les chats', 'Les chiens'],
    ['Lire le livre', 'Voir le film'],
    ['La plage', 'La piscine'],
    ['La musique à fond', 'Le silence total'],
    ['Une série', 'Un film'],
    ['Écrire', 'Dessiner'],
    ['L’été toute l’année comme à Hawaï', 'Quatre vraies saisons'],
    ['Le matin', 'Le soir'],
    ['Un feu de camp avec des chamallows', 'Une soirée pyjama avec des masques de beauté'],
    ['Un mois sans sucre', 'Un mois sans réseaux sociaux'],
    ['Cuisiner comme un chef', 'Chanter comme une star'],
    ['Un talent caché qui impressionne', 'Un rire qui contamine tout le monde'],
    ['Un bisou sous la pluie', 'Un bisou sous les étoiles'],
    ['Un bouquet de ballons', 'Un bouquet de fleurs'],
    ['Une cabane en couvertures dans le salon', 'Un film en plein air'],
    ['Faire le même rêve que moi', 'Revoir tes rêves comme un film'],
    ['Une journée sans rire', 'Une journée sans parler'],
    ['Écrire un livre sur nous', 'Tourner un film sur nous'],
    ['Un chocolat chaud en hiver', 'Une glace en été'],
    ['Un grand câlin debout', 'Un câlin allongés sur le canapé']
  ],

  /* ---------- Qui de nous deux… ---------- */
  qui: [
    's’endort en premier devant un film ?',
    'mange le plus de chocolat ?',
    'passe le plus de temps sur son téléphone ?',
    'fait le plus de câlins ?',
    'envoie le plus de messages ?',
    'met le plus de temps à se préparer ?',
    'arrive le plus souvent en retard ?',
    'chante le plus faux ?',
    'danse le mieux ?',
    'rit le plus fort ?',
    'pleure devant les films Disney ?',
    'ferait le plus de bêtises s’il était Stitch ?',
    'vole le plus la couverture ?',
    'ronfle un tout petit peu ?',
    'oublie le plus de choses ?',
    'pique dans l’assiette de l’autre ?',
    'cuisine le mieux ?',
    'fait le plus de selfies ?',
    'boude le plus longtemps ?',
    's’excuse en premier ?',
    'a la tête la plus dure ?',
    'se perd même avec un GPS ?',
    'gagnerait à cache-cache ?',
    'survivrait le plus longtemps sur une île déserte ?',
    'adopterait un extraterrestre en le prenant pour un chien ?',
    'fait les meilleurs câlins ?',
    'fait les meilleurs bisous ?',
    'dépense le plus d’argent en petites bêtises ?',
    'craque le plus devant les peluches ?',
    'a le plus peur des araignées ?',
    'regarde un film d’horreur sans fermer les yeux ?',
    'crie le plus fort dans les manèges ?',
    'se lève le plus tôt ?',
    'fait le plus la grasse matinée ?',
    'a toujours froid ?',
    'a toujours chaud ?',
    'pourrait manger une pizza entière tout(e) seul(e) ?',
    'fait le plus rire l’autre ?',
    'a le rire le plus contagieux ?',
    'dit le plus de gros mots ?',
    'fait le plus de fautes dans ses messages ?',
    'met le plus d’émojis dans ses messages ?',
    'répond le plus vite aux messages ?',
    'a le plus de photos dans son téléphone ?',
    'est le plus accro aux séries ?',
    'connaît le mieux les films Disney ?',
    'pourrait chanter une chanson Disney en entier ?',
    'ferait le meilleur prof ?',
    'ferait le meilleur chef cuisinier ?',
    'a les goûts musicaux les plus bizarres ?',
    'met le plus de temps à choisir au resto ?',
    'change le plus souvent d’avis ?',
    'se souvient de toutes les dates importantes ?',
    'prépare les meilleures surprises ?',
    'est le plus fleur bleue ?',
    'écrirait le plus beau poème d’amour ?',
    'pleure le plus facilement ?',
    's’énerve le plus vite dans les bouchons ?',
    'piloterait le mieux une voiture de course ?',
    'parle le plus en dormant ?',
    'bouge le plus en dormant ?',
    'prend le plus de place dans le lit ?',
    'finit les phrases de l’autre ?',
    'a le plus de patience ?',
    'casse le plus de choses ?',
    'rate le plus ses photos ?',
    'ferait le meilleur agent secret ?',
    'pourrait devenir célèbre sur TikTok ?',
    'gagnerait un concours de grimaces ?',
    'gagnerait un concours de danse ?',
    'mangerait un insecte pour 100 € ?',
    'oserait sauter en parachute ?',
    'partirait à l’aventure sans hésiter ?',
    'a le plus d’imagination ?',
    'raconte les pires blagues ?',
    'rit à ses propres blagues ?',
    'adopterait Stitch sans hésiter ?',
    'ferait fuir Stitch avec ses bêtises ?',
    'ressemble le plus à Stitch ?',
    'ressemble le plus à Angel ?',
    'ressemble le plus à Lilo ?',
    'est le plus fan de Stitch ?',
    'achèterait tout le rayon peluches ?',
    'dirait oui à un rendez-vous surprise en pleine nuit ?',
    'pleurerait en recevant une lettre d’amour ?',
    'dit « encore cinq minutes » le matin ?',
    'perd le plus souvent ses affaires ?',
    'est le plus organisé ?',
    'fait les listes de courses ?',
    'finit toujours le dernier morceau ?',
    'partage le plus volontiers son dessert ?',
    'choisit toujours la même chose au resto ?',
    'a le plus de chaussures ?',
    'passe le plus de temps dans la salle de bain ?',
    'serait le meilleur parent pour un chaton ?',
    'parle le plus aux animaux ?',
    'se fait le plus de films dans sa tête ?',
    'pose le plus de questions ?',
    'garde le mieux un secret ?',
    'craque le plus vite avant une surprise ?',
    'triche aux jeux de société ?',
    'est le plus mauvais perdant ?',
    'veut toujours gagner ?',
    'pourrait passer une journée entière en pyjama ?',
    'regarde le plus souvent les étoiles ?',
    'prend le plus de photos de l’autre ?',
    'se regarde le plus dans le miroir ?',
    'chante sous la douche ?',
    'danse quand personne ne regarde ?',
    'mange le plus vite ?',
    'mange le plus lentement ?',
    'a le plus de chance ?',
    'dépenserait tout son gain au loto en une semaine ?',
    'ferait le tour du monde ?',
    's’ennuie le plus vite ?',
    'a la meilleure mémoire ?',
    'dit le plus souvent « t’es sûr(e) ? »',
    'se trompe le plus souvent de chemin ?',
    'fait le plus de compliments ?',
    'rougit le plus facilement ?',
    'se met à chanter dès qu’une musique passe ?',
    'regarde le plus de dessins animés ?',
    'a le plus de peluches ?',
    'dort avec une peluche ?',
    'a le plus besoin de câlins ?',
    'est le plus tête en l’air ?',
    'se réveille sans réveil ?',
    'appuie le plus sur « répéter » quand le réveil sonne ?',
    'mange au lit ?',
    'pourrait vivre à Hawaï pour toujours ?',
    'surferait le mieux ?',
    'danserait le mieux le hula ?',
    'gagnerait une bataille de chatouilles ?',
    'est le plus chatouilleux ?',
    'a les mains les plus froides ?',
    'pique la dernière frite ?',
    'survivrait dans le vaisseau de Jumba ?',
    'commande toujours un dessert ?',
    's’endort en voiture ?',
    'met la musique le plus fort ?',
    'écrit les messages les plus longs ?',
    'envoie les vocaux les plus longs ?',
    'utilise le plus de filtres en photo ?',
    'oublie de répondre aux messages ?',
    'sait le mieux consoler l’autre ?',
    'a craqué en premier pour l’autre ?',
    'a fait le premier pas ?',
    'parle le plus de l’autre à ses amis ?'
  ],

  /* ---------- Je n’ai jamais… ---------- */
  jamais: [
    'Je n’ai jamais mangé une pizza entière tout(e) seul(e).',
    'Je n’ai jamais pleuré devant un dessin animé.',
    'Je n’ai jamais chanté à tue-tête sous la douche.',
    'Je n’ai jamais dansé tout(e) seul(e) dans ma chambre.',
    'Je n’ai jamais fait semblant d’être malade pour rester à la maison.',
    'Je n’ai jamais envoyé un message à la mauvaise personne.',
    'Je n’ai jamais dormi plus de 12 heures d’affilée.',
    'Je n’ai jamais fait une nuit blanche.',
    'Je n’ai jamais couru derrière un bus… pour le rater quand même.',
    'Je n’ai jamais parlé tout(e) seul(e) dans la rue.',
    'Je n’ai jamais appelé quelqu’un par le mauvais prénom.',
    'Je n’ai jamais eu un fou rire à un moment très sérieux.',
    'Je n’ai jamais fait une chute ridicule en public.',
    'Je n’ai jamais cassé quelque chose en faisant comme si de rien n’était.',
    'Je n’ai jamais mangé un truc tombé par terre (règle des 5 secondes).',
    'Je n’ai jamais regardé une série entière en un week-end.',
    'Je n’ai jamais eu peur du noir après un film d’horreur.',
    'Je n’ai jamais dormi avec une peluche.',
    'Je n’ai jamais donné un prénom à une peluche.',
    'Je n’ai jamais fait un vœu en voyant une étoile filante.',
    'Je n’ai jamais écrit de journal intime.',
    'Je n’ai jamais gagné un concours.',
    'Je n’ai jamais participé à une compétition sportive.',
    'Je n’ai jamais pris l’avion.',
    'Je n’ai jamais vu la mer en hiver.',
    'Je n’ai jamais nagé dans la mer la nuit.',
    'Je n’ai jamais fait de surf.',
    'Je n’ai jamais dormi sous une tente.',
    'Je n’ai jamais monté à cheval.',
    'Je n’ai jamais été à Disneyland.',
    'Je n’ai jamais fait de karaoké.',
    'Je n’ai jamais chanté devant un public.',
    'Je n’ai jamais joué d’un instrument.',
    'Je n’ai jamais eu de tatouage, même éphémère.',
    'Je n’ai jamais teint mes cheveux d’une couleur flashy.',
    'Je n’ai jamais raté un gâteau au point qu’il soit immangeable.',
    'Je n’ai jamais fait brûler des pâtes.',
    'Je n’ai jamais mis du sel à la place du sucre.',
    'Je n’ai jamais oublié un anniversaire important.',
    'Je n’ai jamais préparé une surprise pour quelqu’un.',
    'Je n’ai jamais reçu de lettre d’amour.',
    'Je n’ai jamais écrit de lettre d’amour.',
    'Je n’ai jamais eu de coup de foudre.',
    'Je n’ai jamais fait le premier pas.',
    'Je n’ai jamais regardé en entier le profil de quelqu’un que je trouvais mignon(ne).',
    'Je n’ai jamais relu une conversation plusieurs fois en souriant.',
    'Je n’ai jamais rougi en recevant un compliment.',
    'Je n’ai jamais effacé un message avant qu’il soit lu.',
    'Je n’ai jamais fait semblant de ne pas avoir vu un message.',
    'Je n’ai jamais oublié le prénom de quelqu’un juste après qu’il s’est présenté.',
    'Je n’ai jamais crié en voyant une araignée.',
    'Je n’ai jamais passé toute une journée en pyjama.',
    'Je n’ai jamais mangé des céréales au dîner.',
    'Je n’ai jamais cuisiné pour impressionner quelqu’un.',
    'Je n’ai jamais imité un accent pour faire rire.',
    'Je n’ai jamais fait une grimace sur une photo officielle.',
    'Je n’ai jamais perdu mes clés.',
    'Je n’ai jamais dormi dans une voiture.',
    'Je n’ai jamais regardé un lever de soleil exprès.',
    'Je n’ai jamais regardé les étoiles allongé(e) dans l’herbe.',
    'Je n’ai jamais fait de bonhomme de neige.',
    'Je n’ai jamais construit de cabane.',
    'Je n’ai jamais fait de bataille d’oreillers.',
    'Je n’ai jamais enchaîné plusieurs films Disney dans la même journée.',
    'Je n’ai jamais regardé Lilo & Stitch plus de trois fois.',
    'Je n’ai jamais essayé de danser le hula.',
    'Je n’ai jamais parlé à un animal comme à une vraie personne.',
    'Je n’ai jamais eu d’animal un peu original (poisson, lapin, tortue…).',
    'Je n’ai jamais rêvé de quelqu’un rencontré le jour même.',
    'Je n’ai jamais rêvé que je volais.',
    'Je n’ai jamais fait un rêve si réel que j’y ai cru au réveil.',
    'Je n’ai jamais ri au point d’en pleurer.',
    'Je n’ai jamais eu le hoquet pendant plus d’une heure.',
    'Je n’ai jamais goûté des escargots.',
    'Je n’ai jamais mangé si épicé que j’en ai pleuré.',
    'Je n’ai jamais acheté un truc inutile juste parce qu’il était mignon.',
    'Je n’ai jamais dépensé tout mon argent en bonbons.',
    'Je n’ai jamais gardé un secret pendant des années.',
    'Je n’ai jamais été pris(e) en flagrant délit de mensonge.',
    'Je n’ai jamais triché à un jeu de société.',
    'Je n’ai jamais boudé toute une journée.',
    'Je n’ai jamais chanté une chanson Disney en entier sans me tromper.',
    'Je n’ai jamais appris une chorégraphie par cœur.',
    'Je n’ai jamais fait une vidéo qui a fait plein de vues.',
    'Je n’ai jamais joué dans un spectacle.',
    'Je n’ai jamais eu un surnom gênant.',
    'Je n’ai jamais oublié ce que j’allais dire en plein milieu d’une phrase.',
    'Je n’ai jamais fait tomber mon téléphone dans l’eau.',
    'Je n’ai jamais cassé l’écran de mon téléphone.',
    'Je n’ai jamais parlé à une plante.',
    'Je n’ai jamais eu le mal de mer.',
    'Je n’ai jamais pleuré de joie.',
    'Je n’ai jamais offert une peluche.',
    'Je n’ai jamais passé une soirée entière à faire des câlins.',
    'Je n’ai jamais rencontré quelqu’un grâce à une appli.',
    'Je n’ai jamais eu les larmes aux yeux en écoutant une chanson.',
    'Je n’ai jamais fait de pique-nique sur la plage.',
    'Je n’ai jamais gagné une peluche à la fête foraine.',
    'Je n’ai jamais mangé une glace en plein hiver.',
    'Je n’ai jamais fait un vœu en soufflant sur un pissenlit.',
    'Je n’ai jamais oublié de répondre à un message pendant plus d’une semaine.'
  ],

  /* ---------- Tu me connais ? (l’un répond pour lui, l’autre devine) ---------- */
  connais: [
    'Quel est ton plat préféré ?',
    'Quelle est ta couleur préférée ?',
    'Quel est ton film Disney préféré ?',
    'Quelle est ta saison préférée ?',
    'Quel est ton animal préféré ?',
    'Quel est ton dessert préféré ?',
    'Quelle est ta boisson préférée ?',
    'Quelle chanson écoutes-tu en boucle en ce moment ?',
    'Quel est ton chanteur ou ta chanteuse préféré(e) ?',
    'Quelle est ta série préférée ?',
    'Quel est ton parfum de glace préféré ?',
    'Quel est ton personnage préféré dans Lilo & Stitch ?',
    'Quel est ton plus grand rêve ?',
    'Quel pays rêves-tu le plus de visiter ?',
    'Quelle est ta plus grande peur ?',
    'Qu’est-ce qui t’énerve le plus ?',
    'Qu’est-ce qui te fait rire à coup sûr ?',
    'Quel émoji utilises-tu le plus ?',
    'Quelle appli ouvres-tu le plus ?',
    'Quel est ton jour préféré de la semaine ?',
    'Quel est ton moment préféré de la journée ?',
    'Quelle était ta matière préférée à l’école ?',
    'Quel métier voulais-tu faire quand tu étais petit(e) ?',
    'Quel était ton dessin animé préféré quand tu étais petit(e) ?',
    'Quel était ton jouet ou ta peluche préférée quand tu étais petit(e) ?',
    'Quel plat de cantine détestais-tu ?',
    'Quelle est ta pizza préférée ?',
    'Quel est ton fast-food préféré ?',
    'Tu es plutôt sucré ou salé ?',
    'Quel légume détestes-tu ?',
    'Quel est ton fruit préféré ?',
    'Quel est ton bonbon préféré ?',
    'Quel est ton petit-déjeuner idéal ?',
    'Quelle est ta tenue préférée pour être à l’aise ?',
    'Quelle est ta pointure ?',
    'Combien mesures-tu ?',
    'Quel est ton signe astrologique ?',
    'Quel est ton deuxième prénom (ou « aucun ») ?',
    'Comment s’appelait ton premier animal (ou « aucun ») ?',
    'Quel est ton sport préféré, à faire ou à regarder ?',
    'Quel est ton jeu vidéo préféré ?',
    'Quel est ton jeu de société préféré ?',
    'Qu’est-ce que tu prends au cinéma : pop-corn, bonbons ou rien ?',
    'Quel est ton genre de film préféré ?',
    'Quel est le dernier film que tu as vu au cinéma ?',
    'Quelle est la dernière chose qui t’a fait pleurer ?',
    'Quel surnom te donnait-on quand tu étais petit(e) ?',
    'Quel super-pouvoir aimerais-tu avoir ?',
    'Quel animal te ressemble le plus ?',
    'Quelle est ta plus grande qualité ?',
    'Quel petit défaut assumes-tu complètement ?',
    'Quelle est la première chose que tu fais en te réveillant ?',
    'Que fais-tu juste avant de dormir ?',
    'Combien d’heures dors-tu en moyenne ?',
    'Tu es plutôt du matin ou du soir ?',
    'Quelle est ton odeur préférée ?',
    'Quelle est ta fleur préférée ?',
    'La mer ou la montagne ?',
    'Quelle est ta ville préférée ?',
    'Quel est ton plus beau voyage ?',
    'Quel cadeau t’a fait le plus plaisir ?',
    'Que t’achèterais-tu en premier si tu gagnais au loto ?',
    'Quel serait ton rendez-vous idéal ?',
    'Sur quelle chanson danses-tu à coup sûr ?',
    'Quelle chanson te rend nostalgique ?',
    'Quel est ton talent caché ?',
    'Quel plat cuisines-tu le mieux ?',
    'Quelle petite phobie as-tu ?',
    'Quel est ton mot préféré ?',
    'Quelle expression dis-tu tout le temps ?',
    'Quel créateur de contenu suis-tu le plus ?',
    'Quel personnage de dessin animé trouves-tu trop mignon ?',
    'Quel est ton moment préféré avec moi jusqu’ici ?',
    'Qu’as-tu remarqué en premier chez moi ?',
    'Qu’est-ce que tu préfères chez moi ?',
    'Quel surnom aimerais-tu me donner ?',
    'Quel plat aimerais-tu que je te cuisine ?',
    'Où aimerais-tu qu’on parte ensemble ?',
    'Qu’est-ce que tu voudrais qu’on fasse ce week-end ?',
    'Quel film choisirais-tu pour une soirée plaid ?',
    'Dans quelle position dors-tu ?',
    'Plutôt chat ou chien ?',
    'Combien de sucres dans ton thé ou ton café (ou « je n’en bois pas ») ?',
    'De quelle couleur est ta brosse à dents ?',
    'Quelle appli utilises-tu pour écouter de la musique ?',
    'Quel est le dernier truc que tu as acheté ?',
    'Qu’y a-t-il sur ton fond d’écran ?',
    'Combien de photos as-tu dans ta galerie, à peu près ?',
    'Combien de batterie te reste-t-il en ce moment ?',
    'Quel a été ton plus gros fou rire ?',
    'Quelle est ta plus grosse honte (racontable) ?',
    'À qui as-tu envoyé ton dernier message, à part moi ?',
    'Quel est ton grignotage de minuit ?',
    'Quel bruit détestes-tu ?',
    'Quelle langue étrangère préfères-tu ?',
    'Que collectionnes-tu (ou collectionnais-tu) ?',
    'Quelle qualité comptes-tu le plus chez quelqu’un ?',
    'À quoi ressemblerait ta maison de rêve ?',
    'Comment s’appelle ton ou ta meilleur(e) ami(e) ?',
    'Quel est ton goûter préféré ?'
  ],

  /* ---------- Sur la même longueur d’onde : [question, 0 =, 10 =] ---------- */
  onde: [
    ['À quel point aimes-tu les surprises ?', 'pas du tout', 'j’adore'],
    ['Tu es plutôt du matin ?', 'zombie au réveil', 'debout avec le soleil'],
    ['À quel point es-tu gourmand(e) ?', 'raisonnable', 'ogre'],
    ['À quel point es-tu câlin(e) ?', 'un peu', 'pieuvre à câlins'],
    ['Tu es plutôt…', 'casanier(ère)', 'aventurier(ère)'],
    ['Les films d’horreur, pour toi…', 'jamais de la vie', 'j’adore'],
    ['À quel point es-tu frileux(se) ?', 'jamais froid', 'toujours gelé(e)'],
    ['À quel point es-tu organisé(e) ?', 'bazar total', 'tout est rangé'],
    ['À quel point es-tu patient(e) ?', 'zéro patience', 'moine zen'],
    ['À quel point es-tu fan de Stitch ?', 'un peu', 'totalement obsédé(e)'],
    ['À quel point aimes-tu danser ?', 'jamais', 'toute la nuit'],
    ['Tu parles plutôt…', 'peu', 'comme un moulin à paroles'],
    ['Ta playlist est plutôt…', 'toute calme', 'à fond'],
    ['À quel point es-tu têtu(e) ?', 'je lâche vite', 'tête de mule'],
    ['À quel point es-tu romantique ?', 'pragmatique', 'fleur bleue'],
    ['Le sport et toi…', 'canapé', 'athlète'],
    ['Devant un film triste, tu es…', 'de pierre', 'une fontaine'],
    ['À quel point aimes-tu cuisiner ?', 'micro-ondes', 'chef étoilé'],
    ['Le piment et toi…', 'pas du tout', 'dragon cracheur de feu'],
    ['À quel point es-tu accro à ton téléphone ?', 'je l’oublie partout', 'il est collé à ma main'],
    ['L’heure et toi…', 'toujours en retard', 'toujours en avance'],
    ['L’argent et toi…', 'écureuil', 'panier percé'],
    ['À quel point aimes-tu la plage ?', 'bof', 'sirène'],
    ['À quel point es-tu chatouilleux(se) ?', 'pas du tout', 'au secours'],
    ['Ton humeur au réveil…', 'grognon', 'rayon de soleil'],
    ['À quel point aimes-tu faire la fête ?', 'pantoufles', 'jusqu’au bout de la nuit'],
    ['À quel point es-tu timide ?', 'pas du tout', 'très'],
    ['À quel point es-tu compétitif(ve) ?', 'cool', 'je dois gagner'],
    ['Les animaux et toi…', 'bof', 'je les adopterais tous'],
    ['Ta mémoire…', 'éléphant', 'poisson rouge'],
    ['À quel point aimes-tu voyager ?', 'chez moi c’est bien', 'nomade'],
    ['Les bisous surprises, pour toi…', 'bof', 'encore !'],
    ['Ton niveau en chant…', 'casserole', 'star'],
    ['Ton niveau en cuisine…', 'je brûle l’eau', 'chef'],
    ['À quel point es-tu rêveur(se) ?', 'les pieds sur terre', 'dans la lune'],
    ['À quel point aimes-tu l’hiver ?', 'je déteste', 'j’adore'],
    ['À quel point es-tu maladroit(e) ?', 'agile comme un chat', 'catastrophe ambulante'],
    ['À quel point te trouves-tu drôle ?', 'sérieux', 'humoriste'],
    ['À quel point es-tu fan de Disney ?', 'un peu', 'Disney addict'],
    ['Les jeux vidéo et toi…', 'jamais', 'gamer'],
    ['La lecture et toi…', 'jamais', 'rat de bibliothèque'],
    ['Ta chambre, en ce moment…', 'nickel', 'tempête tropicale'],
    ['À quel point aimes-tu la pluie ?', 'je déteste', 'j’adore'],
    ['Devant un cadeau emballé…', 'j’attends sagement', 'je secoue le paquet'],
    ['Les photos de toi…', 'je fuis l’objectif', 'star des selfies'],
    ['Face à un insecte…', 'je fuis', 'je l’attrape'],
    ['Plutôt…', 'tout salé', 'tout sucré'],
    ['La sieste et toi…', 'jamais', 'champion(ne) du monde'],
    ['Les manèges à sensations…', 'jamais', 'encore plus haut'],
    ['Goûter un plat inconnu…', 'toujours pareil', 'je goûte tout'],
    ['À quel point es-tu nostalgique ?', 'tourné(e) vers demain', 'je garde tout'],
    ['Les vocaux…', 'que des textos', 'que des vocaux'],
    ['Tu dors plutôt…', 'comme une pierre', 'comme une toupie'],
    ['Les chansons d’amour…', 'bof', 'en boucle'],
    ['Les peluches et toi…', 'pas du tout', 'j’en ai partout'],
    ['Chanter en public…', 'jamais', 'passe-moi le micro'],
    ['À quel point es-tu fatigué(e) en ce moment ?', 'en pleine forme', 'je dors debout'],
    ['À quel point as-tu faim en ce moment ?', 'pas du tout', 'affamé(e)'],
    ['À quel point es-tu heureux(se) aujourd’hui ?', 'bof', 'au top'],
    ['À quel point as-tu envie d’un câlin, là, maintenant ?', 'ça va', 'tout de suite']
  ],

  /* ---------- À cœur ouvert : trois niveaux ---------- */
  coeur: {
    leger: [
      'Quel a été le meilleur moment de ta journée ?',
      'Si tu pouvais dîner avec n’importe qui, qui choisirais-tu ?',
      'Quelle est la chose la plus drôle qui te soit arrivée cette semaine ?',
      'Quel est ton souvenir d’enfance préféré ?',
      'Si tu étais un personnage de Lilo & Stitch, lequel serais-tu ?',
      'Quel talent aimerais-tu avoir du jour au lendemain ?',
      'Quelle chanson te met toujours de bonne humeur ?',
      'Quel est le plus beau cadeau que tu aies reçu ?',
      'Qu’est-ce qui te fait sourire sans raison ?',
      'À quoi ressemble ta journée parfaite, du réveil au coucher ?',
      'Quel film pourrais-tu regarder cent fois ?',
      'Si tu gagnais un voyage demain, où partirais-tu ?',
      'Quel plat pourrais-tu manger tous les jours ?',
      'Quelle est ta petite manie un peu bizarre ?',
      'Que faisais-tu le mercredi après-midi quand tu étais petit(e) ?',
      'Quel est le meilleur conseil qu’on t’ait donné ?',
      'Si tu avais un Stitch à la maison, quelle bêtise le laisserais-tu faire ?',
      'Quelle est la dernière chose qui t’a fait rire aux larmes ?',
      'Quel dessin animé regardais-tu en boucle petit(e) ?',
      'À quelle époque aimerais-tu vivre ?',
      'Si ta vie était un film, quel serait son titre ?',
      'Quelle odeur te rappelle un bon souvenir ?',
      'Qu’est-ce que tu adores faire le dimanche ?',
      'Quel animal aimerais-tu être pendant une journée ?',
      'Quelle est la chose la plus folle que tu aimerais faire un jour ?',
      'Quelle chanson choisirais-tu au karaoké ?',
      'Quel super-pouvoir voudrais-tu pour une journée, et pour faire quoi ?',
      'Quel est ton meilleur souvenir de vacances ?',
      'De quoi es-tu fier(ère) en ce moment ?',
      'Quel métier un peu fou pourrais-tu faire ?',
      'Si on écrivait un livre sur toi, que raconterait le premier chapitre ?',
      'Quelle est ta tenue parfaite pour un jour de pluie ?',
      'Que collectionnerais-tu si tu avais une place infinie ?',
      'Quelle appli inutile adores-tu ?',
      'Que dirais-tu à toi-même à 10 ans ?'
    ],
    doux: [
      'Qu’as-tu pensé la première fois que tu as vu mon profil ?',
      'De quoi te souviens-tu le plus de notre premier rendez-vous ?',
      'À quel moment t’es-tu dit(e) « je l’aime bien » ?',
      'Qu’est-ce qui te fait craquer chez moi ?',
      'Quel est ton moment préféré passé ensemble jusqu’ici ?',
      'Quel surnom aimerais-tu que je te donne ?',
      'Qu’est-ce que je fais qui te fait sourire ?',
      'Quelle chanson te fait penser à moi ?',
      'Qu’aimerais-tu qu’on fasse ensemble ce mois-ci ?',
      'Si on partait en week-end demain, on irait où ?',
      'Quelle est la chose la plus mignonne que je t’aie dite ?',
      'Qu’aimerais-tu que je sache sur toi ?',
      'Ton câlin préféré : quand, où, comment ?',
      'Qu’est-ce qui te rassure quand je suis là ?',
      'Quel rendez-vous de rêve aimerais-tu qu’on vive ?',
      'Quelle photo de nous aimerais-tu qu’on prenne ?',
      'Qu’as-tu ressenti au moment de notre premier bisou ?',
      'Quelle petite tradition rien qu’à nous pourrait-on créer ?',
      'Qu’est-ce qui te donne envie de m’écrire dans la journée ?',
      'Quel petit geste de ma part te touche le plus ?',
      'Si on était des personnages de dessin animé, on serait qui ?',
      'Qu’aimerais-tu qu’on apprenne ensemble ?',
      'Quel film aimerais-tu qu’on regarde blottis l’un contre l’autre ?',
      'À ton avis, qu’est-ce que j’aime le plus chez toi ?',
      'Quelle chose aimerais-tu qu’on fasse chaque semaine ?',
      'Quel compliment t’a le plus touché(e) ?',
      'Comment te sens-tu quand on est ensemble ?',
      'Qu’est-ce qui t’a surpris(e) en apprenant à me connaître ?',
      'Quelle est ta façon préférée de passer une soirée avec moi ?',
      'Si tu devais me décrire en trois mots ?',
      'Quel cadeau tout simple te ferait fondre ?',
      'Qu’aimerais-tu qu’on se promette ?',
      'Quelle aventure aimerais-tu qu’on vive un jour ?',
      'Quel est le moment le plus drôle qu’on ait vécu ensemble ?',
      'Qu’as-tu envie de me dire, là, maintenant ?'
    ],
    profond: [
      'Qu’est-ce qui compte le plus pour toi dans la vie ?',
      'De quoi es-tu le/la plus fier(ère) ?',
      'Qu’est-ce qui te fait vraiment peur ?',
      'Qu’aimerais-tu accomplir dans les cinq prochaines années ?',
      'Quand te sens-tu le plus toi-même ?',
      'Qu’est-ce qui te rend triste et que tu dis rarement ?',
      'Que veut dire « aimer » pour toi ?',
      'Quelle est la leçon la plus importante que la vie t’ait apprise ?',
      'Qu’est-ce qui te fait te sentir aimé(e) ?',
      'Comment aimes-tu qu’on te console quand ça ne va pas ?',
      'Quelle personne t’a le plus inspiré(e) ?',
      'Quel est ton plus grand rêve, même un peu fou ?',
      'Qu’aimerais-tu changer dans le monde ?',
      'Qu’est-ce qui te donne confiance en toi ?',
      'Quel moment de ta vie a tout changé ?',
      'De quoi as-tu besoin quand tu es stressé(e) ?',
      'Que veut dire « Ohana » pour toi, la famille qu’on choisit ?',
      'Quelle est la plus belle chose qu’on ait faite pour toi ?',
      'Qu’est-ce que tu n’oses pas encore me demander ?',
      'Que puis-je faire quand tu es de mauvaise humeur ?',
      'Qu’est-ce qui te rend unique, selon toi ?',
      'Quelle est ta plus belle qualité en amour ?',
      'Qu’as-tu appris sur toi récemment ?',
      'Quelle chose voudrais-tu ne jamais perdre ?',
      'Quelle personne veux-tu devenir ?',
      'Qu’est-ce qui te fait te sentir en sécurité ?',
      'Qu’aimerais-tu qu’on construise ensemble ?',
      'Qu’est-ce qui te touche le plus quand on prend soin de toi ?',
      'Quel souvenir voudrais-tu garder pour toujours ?',
      'Qu’as-tu envie de vivre avec moi plus tard ?',
      'Comment imagines-tu notre couple dans un an ?',
      'Qu’est-ce qui te fait te sentir libre ?',
      'Que voudrais-tu que les gens retiennent de toi ?',
      'Quel rêve n’as-tu encore jamais dit à personne ?',
      'Qu’est-ce qui t’a donné envie de dire oui à notre histoire ?'
    ]
  },

  /* ---------- Action ou vérité ---------- */
  verites: [
    'Quelle est la première chose que tu as remarquée chez moi ?',
    'Quel est ton plus gros fou rire de l’année ?',
    'As-tu déjà inventé une excuse pour éviter une sortie ? Raconte.',
    'Quelle est ta plus grande honte au collège ?',
    'Quel est le truc le plus bizarre que tu fais quand tu es seul(e) ?',
    'Quel est le dernier petit mensonge que tu as dit ?',
    'Quelle est la chose la plus inutile que tu aies achetée ?',
    'Quelle chanson honteuse écoutes-tu en cachette ?',
    'Quel surnom secret me donnes-tu dans ta tête ?',
    'As-tu parlé de moi à tes amis ? Qu’as-tu dit ?',
    'Qu’as-tu pensé de moi après notre premier rendez-vous ?',
    'Quelle est ta peur la plus ridicule ?',
    'Quel est le rêve le plus bizarre que tu aies fait ?',
    'Quel personnage de dessin animé trouves-tu mignon en secret ?',
    'Qu’est-ce que tu ne supportes pas chez les autres ?',
    'Quel talent inutile as-tu ?',
    'Quand as-tu pleuré pour la dernière fois ?',
    'Qu’est-ce que tu préfères chez moi, physiquement ?',
    'Qu’est-ce que tu préfères dans mon caractère ?',
    'As-tu déjà relu nos messages ? Lesquels ?',
    'Quel est ton plus grand défaut, honnêtement ?',
    'Qu’est-ce qui t’agace un tout petit peu chez moi ?',
    'Qu’aimerais-tu que je fasse plus souvent ?',
    'Quel est ton plaisir coupable ?',
    'As-tu déjà fait semblant d’aimer un cadeau ?',
    'Quelle est la plus grosse bêtise que tu aies faite enfant ?',
    'Quelle célébrité te fait craquer ?',
    'Quel est le message le plus gênant que tu aies envoyé ?',
    'Quelle a été ta pire tenue de tous les temps ?',
    'As-tu déjà eu un fou rire en plein cours ?',
    'Que fais-tu pour te consoler quand ça ne va pas ?',
    'Quel est ton petit rituel du soir ?',
    'As-tu déjà parlé à une peluche ? Laquelle ?',
    'Quelle chose n’as-tu jamais osé dire à personne ? (joker autorisé !)',
    'Tu me mettrais combien sur 10 en câlins ?',
    'Quelle est ta plus grande fierté ?',
    'Qu’est-ce qui te fait rougir ?',
    'Quel serait ton rendez-vous parfait avec moi ?',
    'Combien de fois as-tu pensé à moi aujourd’hui ?',
    'Quel moment avec moi t’a le plus gêné(e) ?',
    'Quelle est la dernière chose que tu as cherchée sur ton téléphone ?',
    'Montre la dernière photo de ta galerie et raconte-la.',
    'Quelle appli cacherais-tu si je prenais ton téléphone ?',
    'Quelle est la chose la plus romantique que tu aies faite ?',
    'As-tu déjà écrit mon prénom quelque part en cachette ?',
    'Quelle chanson voudrais-tu comme « notre chanson » ?',
    'Qu’as-tu ressenti en recevant mon premier message ?',
    'As-tu regardé mon profil en entier ? Jusqu’où ?',
    'Quel émoji me correspond le mieux ?',
    'Qu’est-ce qui te manque le plus quand on n’est pas ensemble ?',
    'Quelle est la chose que tu fais le mieux ?',
    'Quelle est ta plus grande qualité selon tes amis ?',
    'Que faisais-tu juste avant qu’on joue ?',
    'Quelle est la chose la plus bizarre que tu aies mangée ?',
    'Qui est ton personnage Disney préféré, et pourquoi ?',
    'Quelle est ta plus grande peur en amour ?',
    'Quand as-tu eu le plus le trac ?',
    'Qu’est-ce qui t’a fait sourire aujourd’hui ?',
    'Quelle est l’excuse la plus bidon que tu aies inventée ?',
    'Que changerais-tu dans ta journée d’hier ?',
    'Qu’est-ce qui te fait craquer chez quelqu’un ?',
    'Quelle est la chose la plus gentille que tu aies faite pour un inconnu ?',
    'Tu préfères que je te chante une chanson ou que je t’écrive un poème ?',
    'Quel est ton plus grand regret de la semaine ?',
    'Qu’aimerais-tu que je t’offre ?',
    'Quel film t’a fait le plus peur ?',
    'Tu dors avec quoi : peluche, doudou, rien ?',
    'Que penses-tu vraiment de mes blagues ?',
    'Quel compliment n’as-tu jamais osé me faire ?',
    'Qu’est-ce qui te rend heureux(se), là, tout de suite ?'
  ],
  actions: [
    'Fais-moi un câlin de 20 secondes.',
    'Fais-moi un bisou sur la joue.',
    'Fais-moi trois compliments sans hésiter.',
    'Imite Stitch pendant 30 secondes.',
    'Danse le hula pendant 20 secondes.',
    'Chante le refrain d’une chanson Disney.',
    'Fais ta plus belle grimace et garde-la 10 secondes.',
    'Raconte une blague, même nulle.',
    'Masse-moi les épaules pendant une minute.',
    'Dessine-moi en 30 secondes.',
    'Parle avec l’accent de ton choix jusqu’à ton prochain tour.',
    'Fais-moi une déclaration façon film romantique.',
    'Envoie-moi un message trop mignon, maintenant.',
    'Prends un selfie grimace avec moi.',
    'Mime ton animal préféré.',
    'Fais-moi rire en moins de 30 secondes.',
    'Improvise une chorégraphie de 15 secondes.',
    'Chante « Joyeux anniversaire » comme un chanteur d’opéra.',
    'Donne-moi un surnom mignon et utilise-le jusqu’à la fin du jeu.',
    'Fais-moi un bisou sur le nez.',
    'Prends la voix de Stitch et dis « Ohana ».',
    'Tiens-moi la main jusqu’à ton prochain tour.',
    'Fais-moi un câlin surprise dans les deux prochaines minutes.',
    'Raconte notre rencontre comme un conte de fées.',
    'Fais une imitation de moi.',
    'Écris un petit mot doux sur un papier et donne-le-moi.',
    'Fais 10 squats en chantant.',
    'Montre-moi ta danse de la victoire.',
    'Invente un poème de quatre vers sur moi.',
    'Joue un présentateur météo qui annonce une pluie de câlins.',
    'Fais-moi un bisou esquimau, nez contre nez.',
    'Regarde-moi dans les yeux 30 secondes sans rire.',
    'Fais-moi un compliment en chantant.',
    'Mime une scène de Lilo & Stitch : je dois deviner laquelle.',
    'Fais-moi une révérence en m’appelant « Votre Altesse ».',
    'Prends une photo de nous deux trop mignonne.',
    'Raconte ton rêve de la nuit dernière, avec les gestes.',
    'Choisis une chanson et danse un slow avec moi.',
    'Fais un bisou à la peluche la plus proche.',
    'Parle comme un robot jusqu’à ton prochain tour.',
    'Fais un défilé de mode avec ce que tu portes.',
    'Fais-moi un bisou papillon avec tes cils.',
    'Dis-moi « aloha » de la façon la plus mignonne possible.',
    'Imite un animal marin, je dois deviner lequel.',
    'Masse-moi les mains pendant une minute.',
    'Fais-moi un baisemain, comme un prince.',
    'Invente une chanson avec mon prénom dedans.',
    'Montre-moi ta pire photo et laisse-moi rire.',
    'Fais-moi un câlin géant en me soulevant (si tu peux !).',
    'Coiffe-moi pendant une minute.',
    'Fais un compliment à mon sourire.',
    'Fais-moi une promesse toute mignonne.',
    'Dessine un cœur sur ma main avec ton doigt.',
    'Fais la chenille autour de la pièce.',
    'Raconte une histoire drôle de ton enfance.',
    'Fais un cri d’animal au choix, très fort.',
    'Sors de l’eau au ralenti comme dans un film (même sans eau).',
    'Chante une chanson d’Elvis, ou fais semblant.',
    'Fais-moi un petit massage de la tête.',
    'Offre-moi un objet à portée de main comme si c’était un trésor.',
    'Invite-moi à un premier rendez-vous, en mieux que la vraie fois.',
    'Mets une musique et fais-moi danser.',
    'Dis-moi trois choses que tu aimes chez moi.',
    'Fais un bisou sur chacune de mes joues.',
    'Écris mon prénom en l’air avec ton nez.',
    'Prends une pose de super-héros et tiens-la 15 secondes.',
    'Fais-moi un câlin de Stitch, en grognant comme lui.',
    'Parle-moi comme à un bébé chat pendant 20 secondes.',
    'Fais-moi une déclaration en trois mots seulement.',
    'Choisis l’action que je devrai faire à mon prochain tour.'
  ],

  /* ---------- Stitch dessine : mots à dessiner ---------- */
  dessin: [
    'Stitch', 'Ananas', 'Palmier', 'Planche de surf', 'Ukulélé', 'Tortue', 'Vague', 'Coquillage', 'Collier de fleurs',
    'Noix de coco', 'Volcan', 'Fusée', 'Soucoupe volante', 'Extraterrestre', 'Poisson', 'Glace', 'Pastèque', 'Hamac',
    'Soleil', 'Arc-en-ciel', 'Cœur', 'Bisou', 'Bague', 'Lettre d’amour', 'Rose', 'Cadeau', 'Chocolat', 'Câlin',
    'Gâteau d’anniversaire', 'Bougie', 'Ballon', 'Nounours', 'Chat', 'Chien', 'Lapin', 'Cochon', 'Girafe', 'Éléphant',
    'Pingouin', 'Pieuvre', 'Requin', 'Dauphin', 'Papillon', 'Escargot', 'Abeille', 'Coccinelle', 'Hibou', 'Licorne',
    'Dinosaure', 'Dragon', 'Singe', 'Crabe', 'Serpent', 'Grenouille', 'Vache', 'Poule', 'Cheval', 'Canard', 'Souris',
    'Lion', 'Zèbre', 'Baleine', 'Pizza', 'Burger', 'Frites', 'Croissant', 'Banane', 'Fraise', 'Cerise', 'Pomme',
    'Carotte', 'Champignon', 'Œuf au plat', 'Sandwich', 'Sucette', 'Donut', 'Crêpe', 'Pop-corn', 'Tasse', 'Fourchette',
    'Parapluie', 'Lunettes', 'Chaussure', 'Chapeau', 'Couronne', 'Clé', 'Cadenas', 'Lampe', 'Téléphone', 'Ordinateur',
    'Appareil photo', 'Télévision', 'Guitare', 'Tambour', 'Livre', 'Crayon', 'Ciseaux', 'Horloge', 'Réveil', 'Lit',
    'Chaise', 'Maison', 'Château', 'Tente', 'Arbre', 'Fleur', 'Cactus', 'Nuage', 'Éclair', 'Étoile', 'Lune',
    'Bonhomme de neige', 'Sapin de Noël', 'Citrouille', 'Fantôme', 'Voiture', 'Vélo', 'Avion', 'Bateau', 'Train',
    'Montgolfière', 'Trottinette', 'Pique-nique', 'Plage', 'Piscine', 'Cinéma', 'Manège', 'Toboggan', 'Balançoire',
    'Cerf-volant', 'Feu de camp', 'Montagne', 'Île déserte', 'Sirène', 'Pirate', 'Trésor', 'Princesse', 'Robot',
    'Astronaute', 'Sorcière', 'Vampire', 'Chaussette', 'Brosse à dents', 'Bonbon', 'Escargot de mer', 'Étoile de mer',
    'Hippocampe', 'Phare', 'Ancre', 'Parasol', 'Seau et pelle', 'Château de sable', 'Tong', 'Maillot de bain',
    'Lunettes de soleil', 'Crème solaire', 'Hélicoptère', 'Moto', 'Sous-marin', 'Igloo'
  ],

  /* ---------- Le mime : un maximum en 60 secondes ---------- */
  mime: [
    'Stitch qui fait des bêtises', 'Danser le hula', 'Surfer une grosse vague', 'Jouer du ukulélé', 'Nourrir un poisson',
    'Un extraterrestre qui atterrit', 'Elvis Presley', 'Elsa qui fait de la glace', 'Simba qui rugit', 'Ariel la petite sirène',
    'Aladdin sur son tapis volant', 'Peter Pan qui vole', 'Cendrillon qui perd sa chaussure', 'Blanche-Neige qui croque la pomme',
    'Le génie de la lampe', 'Donald en colère', 'Winnie l’ourson qui mange du miel', 'Buzz l’Éclair', 'Nemo qui cherche son papa',
    'Se brosser les dents', 'Faire la vaisselle', 'Passer l’aspirateur', 'Prendre un selfie', 'Envoyer un message',
    'Se réveiller en retard', 'Rater le bus', 'Couper des oignons', 'Manger des spaghettis', 'Boire un chocolat trop chaud',
    'Faire du vélo', 'Conduire une voiture', 'Faire du ski', 'Nager', 'Plonger', 'Pêcher', 'Jardiner', 'Faire du yoga',
    'Faire un gâteau', 'Ouvrir un cadeau', 'Souffler des bougies', 'Jongler', 'Faire du patin à glace', 'Jouer au tennis',
    'Jouer au foot', 'Boxer', 'Danser la salsa', 'Danser un slow', 'Marcher sur un Lego', 'Se cogner le petit orteil',
    'Avoir le hoquet', 'Éternuer', 'Bâiller', 'Ronfler', 'Avoir très froid', 'Avoir très chaud', 'Voir une araignée',
    'Un singe', 'Un pingouin', 'Un kangourou', 'Un éléphant', 'Un serpent', 'Une poule', 'Un chat qui fait sa toilette',
    'Un chien qui remue la queue', 'Un lion', 'Une grenouille', 'Un crabe', 'Une pieuvre', 'Un dauphin', 'Un papillon',
    'Un flamant rose', 'Une tortue', 'Un gorille', 'Une girafe', 'Un poisson hors de l’eau', 'Un pompier', 'Un policier',
    'Un chirurgien', 'Un coiffeur', 'Un serveur', 'Un magicien', 'Un pilote d’avion', 'Un astronaute', 'Un photographe',
    'Un chef d’orchestre', 'Un cow-boy', 'Un pirate', 'Un clown', 'Une danseuse étoile', 'Un prof', 'Un boulanger',
    'Un facteur', 'Un DJ', 'Envoyer un bisou volant', 'Tomber amoureux', 'Avoir des papillons dans le ventre',
    'Faire un câlin à un arbre', 'Écrire une lettre d’amour', 'Offrir des fleurs', 'Chanter une sérénade',
    'Un premier rendez-vous', 'Se réconcilier après une dispute', 'Être jaloux', 'Être gêné', 'Avoir le fou rire',
    'Bouder', 'Être très fier', 'S’ennuyer', 'Être surpris', 'Avoir sommeil', 'Être déçu', 'Un zombie', 'Un robot',
    'Un fantôme', 'Une statue', 'Un mannequin qui défile', 'Un super-héros', 'Une sorcière sur son balai', 'Un vampire',
    'Un dinosaure', 'Une momie', 'Un ninja', 'Un chevalier', 'Une princesse', 'Un bébé', 'Un touriste perdu',
    'Un surfeur qui tombe', 'Gonfler un ballon', 'Faire un château de sable', 'Mettre de la crème solaire',
    'Porter une valise très lourde', 'Attraper un taxi', 'Faire du stop', 'Monter un escalier très raide',
    'Marcher sur du sable brûlant', 'Se faire piquer par une abeille', 'Faire un karaoké', 'Jouer de la batterie',
    'Faire du trampoline', 'Monter à cheval', 'Faire du hula hoop', 'Tirer à l’arc', 'Être dans un manège qui tourne',
    'Faire des crêpes', 'Promener un chien qui tire', 'Prendre une photo de groupe'
  ],

  /* ---------- 5 secondes chrono : trois réponses en 5 secondes ---------- */
  cinq: [
    'Trois personnages de Lilo & Stitch', 'Trois films Disney', 'Trois fruits jaunes', 'Trois animaux qui vivent dans la mer',
    'Trois choses qu’on emporte à la plage', 'Trois prénoms qui commencent par K', 'Trois prénoms qui commencent par E',
    'Trois couleurs de l’arc-en-ciel', 'Trois pays d’Europe', 'Trois instruments de musique', 'Trois desserts',
    'Trois choses qui volent', 'Trois marques de voitures', 'Trois sports avec un ballon', 'Trois choses qu’on trouve dans une cuisine',
    'Trois animaux à rayures', 'Trois légumes verts', 'Trois super-héros', 'Trois princesses Disney', 'Trois méchants de Disney',
    'Trois choses rouges', 'Trois choses qui piquent', 'Trois jeux de société', 'Trois chanteurs ou chanteuses français',
    'Trois capitales', 'Trois métiers où l’on porte un uniforme', 'Trois choses qu’on fait le matin', 'Trois mots qui riment avec « amour »',
    'Trois mots qui riment avec « bisou »', 'Trois fromages', 'Trois garnitures de pizza', 'Trois parfums de glace',
    'Trois choses qu’on met dans un sac', 'Trois applis sur ton téléphone', 'Trois dessins animés', 'Trois choses froides',
    'Trois animaux de la ferme', 'Trois oiseaux', 'Trois insectes', 'Trois choses qui font du bruit', 'Trois fleurs',
    'Trois arbres', 'Trois moyens de transport', 'Trois vêtements d’hiver', 'Trois choses qu’on voit dans le ciel',
    'Trois mots en anglais', 'Trois plats italiens', 'Trois choses qu’on offre à la Saint-Valentin', 'Trois chansons d’amour',
    'Trois séries', 'Trois personnages de Toy Story', 'Trois animaux qui commencent par C', 'Trois choses rondes',
    'Trois choses dans une salle de bain', 'Trois marques de vêtements', 'Trois jeux vidéo', 'Trois choses qui sentent bon',
    'Trois choses qui sentent mauvais', 'Trois animaux d’Afrique', 'Trois îles', 'Trois mots hawaïens', 'Trois choses bleues comme Stitch',
    'Trois choses roses comme Angel', 'Trois fêtes de l’année', 'Trois choses qu’on fait en vacances', 'Trois bonbons',
    'Trois choses qu’on met sur une crêpe', 'Trois émojis que tu utilises souvent', 'Trois choses qui te font rire',
    'Trois qualités de la personne en face de toi', 'Trois choses que vous avez déjà faites ensemble', 'Trois surnoms mignons',
    'Trois choses qu’on trouve dans l’espace', 'Trois planètes', 'Trois pays d’Asie', 'Trois sports d’hiver',
    'Trois choses qu’on range dans un frigo', 'Trois boissons chaudes', 'Trois choses qu’on emporte en camping',
    'Trois animaux qui sautent', 'Trois contes de fées', 'Trois mots qui commencent par « ch »', 'Trois choses carrées',
    'Trois personnages de Harry Potter', 'Trois chansons de dessins animés', 'Trois choses qui brillent', 'Trois choses toutes molles',
    'Trois animaux qui vivent la nuit', 'Trois choses qu’on fait avec les mains', 'Trois métiers de la santé',
    'Trois animaux avec une carapace ou une coquille', 'Trois choses qu’on trouve sur une plage', 'Trois choses qui fondent',
    'Trois appareils électriques', 'Trois langues parlées dans le monde', 'Trois célébrités', 'Trois décorations de sapin de Noël',
    'Trois idées de rendez-vous', 'Trois choses que tu aimes chez toi', 'Trois raisons de faire un câlin, tout de suite'
  ],

  /* ---------- Quiz Stitch : [question, [4 réponses], bonne, le petit plus] ---------- */
  quiz: [
    ['Quel est le numéro d’expérience de Stitch ?', ['624', '625', '626', '627'], 2, 'Stitch est l’expérience 626 du docteur Jumba.'],
    ['Qui a créé Stitch ?', ['Pikly', 'Jumba', 'Cobra Bubbles', 'Gantu'], 1, 'Le docteur Jumba Jookiba, un savant un peu fou.'],
    ['Sur quelle île hawaïenne vivent Lilo et Nani ?', ['Oahu', 'Maui', 'Kauai', 'Molokai'], 2, 'Toute l’histoire se passe sur l’île de Kauai.'],
    ['Comment s’appelle la grande sœur de Lilo ?', ['Nani', 'Moana', 'Leilani', 'Kaia'], 0, 'Nani s’occupe de Lilo toute seule.'],
    ['Que veut dire « Ohana » ?', ['Amour', 'Famille', 'Maison', 'Amitié'], 1, '« Ohana signifie famille. Famille signifie que personne ne doit être abandonné, ni oublié. »'],
    ['Comment s’appelle la poupée de Lilo ?', ['Souillon', 'Frimousse', 'Chiffon', 'Mimi'], 0, 'Lilo l’a fabriquée elle-même.'],
    ['Comment s’appelle le poisson que Lilo nourrit ?', ['Nemo', 'Pudge', 'Bubulle', 'Kiki'], 1, 'Pudge, un gros poisson qui vit près de la plage.'],
    ['Que donne Lilo à son poisson ?', ['Du pain', 'Un sandwich au beurre de cacahuète', 'Des frites', 'Du riz'], 1, 'Elle est persuadée qu’il contrôle la météo !'],
    ['Quel est le chanteur préféré de Lilo ?', ['Michael Jackson', 'Elvis Presley', 'Bob Marley', 'Frank Sinatra'], 1, 'Elle veut même faire de Stitch un « bon citoyen » comme Elvis.'],
    ['Pour quel animal Stitch se fait-il passer ?', ['Un chat', 'Un chien', 'Un koala', 'Un lapin'], 1, 'Il se fait passer pour un chien un peu bizarre.'],
    ['Où Lilo adopte-t-elle Stitch ?', ['Dans un refuge pour animaux', 'À la plage', 'Dans une animalerie', 'Au zoo'], 0, 'Elle le choisit alors que personne ne veut de lui.'],
    ['Quel est le numéro d’expérience d’Angel ?', ['624', '625', '628', '007'], 0, 'Angel, l’expérience 624, et Stitch, la 626.'],
    ['De quelle couleur est Angel ?', ['Violette', 'Rose', 'Verte', 'Jaune'], 1, 'Rose, avec de longues antennes.'],
    ['Comment s’appelle l’extraterrestre à un seul œil qui accompagne Jumba ?', ['Pikly', 'Gantu', 'Ruben', 'Hämsterviel'], 0, 'Pikly, spécialiste (autoproclamé) de la planète Terre.'],
    ['Qui vient vérifier que Nani s’occupe bien de Lilo ?', ['Cobra Bubbles', 'David', 'Pikly', 'Gantu'], 0, 'Cobra Bubbles, travailleur social en costume noir.'],
    ['Quel ami de Nani adore le surf ?', ['David', 'Keoni', 'Kai', 'Mano'], 0, 'David emmène toute la petite famille surfer.'],
    ['Combien de bras Stitch peut-il avoir ?', ['2', '4', '6', '8'], 1, 'Il peut rentrer deux de ses bras, ses antennes et ses piquants.'],
    ['Pourquoi Stitch ne sait-il pas nager ?', ['Il a peur de l’eau', 'Il est trop dense et coule', 'Il est allergique au sel', 'Il n’a jamais appris'], 1, 'Il est bien trop lourd pour sa taille : il coule comme une pierre.'],
    ['En quelle année est sorti le dessin animé Lilo & Stitch ?', ['1998', '2002', '2005', '2010'], 1, 'Il est sorti en 2002.'],
    ['En quelle année est sorti le film Lilo & Stitch avec de vrais acteurs ?', ['2023', '2024', '2025', '2026'], 2, 'Il est sorti au cinéma en 2025.'],
    ['Quelle danse Lilo apprend-elle ?', ['La salsa', 'Le hula', 'Le tango', 'La samba'], 1, 'Le hula, la danse traditionnelle hawaïenne.'],
    ['Quel conte Stitch lit-il en se sentant perdu ?', ['Le Vilain Petit Canard', 'Cendrillon', 'Pinocchio', 'Le Petit Prince'], 0, 'L’histoire d’un petit qui cherche sa famille, comme lui.'],
    ['Quel capitaine géant poursuit Stitch ?', ['Le capitaine Crochet', 'Le capitaine Gantu', 'Le capitaine Haddock', 'Le capitaine Flam'], 1, 'Gantu, un grand capitaine qui ressemble à une baleine.'],
    ['Quel est le nom de famille de Lilo ?', ['Pelekai', 'Kawena', 'Kahale', 'Makoa'], 0, 'Lilo Pelekai.'],
    ['Qui prête sa voix à Stitch en version originale ?', ['Chris Sanders', 'Tom Hanks', 'Robin Williams', 'Eddie Murphy'], 0, 'Chris Sanders a aussi coréalisé le film.'],
    ['Que veut dire « Aloha » ?', ['Bonjour, au revoir… et amour', 'Merci', 'Bon appétit', 'Bonne nuit'], 0, 'Un seul mot pour dire bonjour, au revoir et affection.'],
    ['Que veut dire « Mahalo » en hawaïen ?', ['Merci', 'Pardon', 'Bonjour', 'Au secours'], 0, 'Mahalo : merci.'],
    ['Comment s’appelle le collier de fleurs hawaïen ?', ['Un lei', 'Un poke', 'Un luau', 'Un tiki'], 0, 'On l’offre pour souhaiter la bienvenue.'],
    ['Quel petit instrument à quatre cordes est typique d’Hawaï ?', ['La guitare', 'Le banjo', 'Le ukulélé', 'La mandoline'], 2, 'Le ukulélé, que Stitch adore gratter.'],
    ['Quelle est la capitale d’Hawaï ?', ['Hilo', 'Honolulu', 'Lahaina', 'Kapaa'], 1, 'Honolulu, sur l’île d’Oahu.'],
    ['En quelle année Hawaï est-il devenu un État américain ?', ['1898', '1959', '1969', '1776'], 1, 'Le 50e État, en 1959.'],
    ['Quel sport les anciens Hawaïens pratiquaient-ils déjà sur des planches de bois ?', ['Le skate', 'Le surf', 'Le ski', 'Le curling'], 1, 'Le surf a une très longue histoire à Hawaï.'],
    ['Pour quoi Stitch a-t-il été conçu au départ ?', ['Faire la cuisine', 'Tout détruire', 'Garder les enfants', 'Chanter'], 1, 'Mais il découvre l’Ohana… et change.'],
    ['Quel volcan hawaïen est l’un des plus actifs du monde ?', ['L’Etna', 'Le Kilauea', 'Le Vésuve', 'Le Fuji'], 1, 'Le Kilauea, sur la Grande Île.'],
    ['Avec quoi Lilo prend-elle ses photos dans le film ?', ['Un appareil photo', 'Un téléphone', 'Une tablette', 'Un caméscope'], 0, 'Elle photographie les touristes sur la plage.']
  ],

  /* ---------- La roue des câlins : [émoji, sur la roue, en entier] ---------- */
  gages: [
    ['🤗', 'Câlin 20 s', 'Un câlin de 20 secondes, sans lâcher !'],
    ['😘', 'Bisou joue', 'Un bisou sur la joue.'],
    ['💆', 'Massage', 'Un massage des épaules d’une minute.'],
    ['💬', '3 compliments', 'Trois compliments, là, tout de suite.'],
    ['🎤', 'Chanson', 'Chante le refrain de ta chanson préférée.'],
    ['💃', 'Hula', 'Danse le hula pendant 15 secondes.'],
    ['🙃', 'Grimace', 'Ta plus belle grimace pendant 10 secondes.'],
    ['📸', 'Selfie', 'Un selfie trop mignon à deux.'],
    ['🐧', 'Esquimau', 'Un bisou esquimau, nez contre nez.'],
    ['🦋', 'Papillon', 'Un bisou papillon avec tes cils.'],
    ['🍫', 'Douceur', 'Offre une petite douceur : bonbon, carré de chocolat…'],
    ['🎁', 'Bon pour…', 'Écris un « bon pour… » à offrir à l’autre.'],
    ['👽', 'Stitch', 'Imite Stitch pendant 20 secondes.'],
    ['🌺', 'Déclaration', 'Une déclaration en trois phrases.'],
    ['🤝', 'Main', 'Main dans la main jusqu’au prochain tour.'],
    ['🎶', 'Slow', 'Un slow sur une chanson entière.'],
    ['🍿', 'Film', 'Tu choisis le film de la prochaine soirée plaid.'],
    ['✍️', 'Mot doux', 'Écris un mot doux et cache-le quelque part.'],
    ['🥞', 'Petit-déj', 'Promets un petit-déjeuner surprise.'],
    ['😂', 'Blague', 'Raconte ta meilleure blague.'],
    ['🔮', 'Voyance', 'Prédis-nous un truc génial pour cette année.'],
    ['🎨', 'Portrait', 'Dessine l’autre en 30 secondes.'],
    ['🪶', 'Chatouilles', 'Dix secondes de chatouilles, tout en douceur.'],
    ['👑', 'Roi / Reine', 'L’autre est roi ou reine pendant 5 minutes.'],
    ['🧸', 'Câlin ours', 'Un câlin d’ours en grognant comme Stitch.'],
    ['🎙️', 'Vocal', 'Envoie un message vocal tout doux à l’autre.'],
    ['🍝', 'Chef', 'Tu cuisines le prochain repas.'],
    ['🍀', 'Joker', 'Pas de gage pour toi : profites-en !'],
    ['🔁', 'Rejoue', 'Refais tourner la roue !'],
    ['🏝️', 'Sortie', 'Propose un rendez-vous pour cette semaine.'],
    ['🤫', 'Secret', 'Confie un petit secret.'],
    ['🌙', 'Étoiles', 'Promets une soirée à regarder les étoiles.'],
    ['🎧', 'Playlist', 'Ajoute une chanson à votre playlist.'],
    ['💐', 'Fleur', 'Offre une fleur, même dessinée.'],
    ['👀', 'Regard', 'Trente secondes les yeux dans les yeux sans rire.'],
    ['🫶', 'Merci', 'Dis merci pour trois choses.'],
    ['🐥', 'Pingouin', 'Marche comme un pingouin jusqu’à la porte.'],
    ['🧃', 'Service', 'Va chercher à boire pour l’autre.'],
    ['🙊', 'Silence', 'Plus le droit de parler pendant une minute.'],
    ['💋', 'Surprise', 'Un bisou surprise dans les cinq minutes.']
  ],

  /* ---------- Idée de sortie : trois dés ---------- */
  sortie: {
    ou: [
      'Au bord de la mer', 'Dans un parc', 'Au cinéma', 'Dans un café tout mignon', 'Chez l’un de nous deux', 'En forêt',
      'À la fête foraine', 'Au bowling', 'Dans un musée', 'En haut d’un joli point de vue', 'Au marché', 'Dans une librairie',
      'Au bord d’un lac', 'Dans un resto qu’on ne connaît pas', 'Dans une salle d’arcade', 'Sur la plage au coucher du soleil',
      'Dans un salon de thé', 'Dans un parc d’attractions', 'À la patinoire', 'Dans un aquarium', 'Dans la ville d’à côté',
      'En pleine nature', 'Au zoo', 'Dans une crêperie', 'Sous un plaid, dans le salon'
    ],
    quoi: [
      'un pique-nique', 'une balade main dans la main', 'un concours de selfies', 'un goûter de crêpes', 'une séance photo',
      'une chasse au trésor', 'un karaoké', 'des cookies maison', 'un marathon de films', 'un dessin l’un de l’autre',
      'goûter un truc jamais goûté', 'une balade à vélo', 'regarder les étoiles', 'un puzzle', 'une glace géante à partager',
      'un tour de manège', 'une soirée jeux', 'une balade de nuit', 'une lettre à ouvrir dans un an', 'un spa maison',
      'un blind-test', 'un concours de châteaux de sable', 'une cabane en couvertures', 'apprendre une danse',
      'une playlist rien qu’à nous'
    ],
    plus: [
      'en tenues assorties', 'sans téléphone', 'avec un petit cadeau surprise', 'en ne parlant qu’en chantant',
      'avec 10 € de budget maximum', 'avec une photo toutes les 30 minutes', 'avec un bisou à chaque feu rouge',
      'en se racontant un souvenir d’enfance', 'déguisés en Stitch et Angel', 'avec un pique-nique préparé en secret',
      'et c’est l’autre qui choisit tout', 'en se tenant la main tout le temps', 'avec une playlist spéciale',
      'au lever du soleil', 'au coucher du soleil', 'sous la pluie, avec un parapluie pour deux',
      'avec des lunettes de soleil ridicules', 'en goûtant quelque chose de nouveau', 'avec un mot doux caché',
      'en jouant les touristes', 'en ne se faisant que des compliments', 'avec un selfie devant chaque truc rigolo',
      'avec une course pour le retour', 'et on finit par un câlin d’une minute', 'et le perdant du chifoumi offre la glace'
    ]
  }
};
